name: Delete S3 Bucket

on:
  pull_request:
    types:
      - closed

env:
  S3-BUCKET: ${{secrets.S3_BUCKET}}-${{ github.event.pull_request.number }}

jobs:
  delete_bucket:
    runs-on: ubuntu-latest
    environment:
        name: nonprod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Delete S3 Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 rb s3://${{env.S3-BUCKET}} --force