name: "PULL REQUEST to S3"

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

env:
  S3-BUCKET: ${{secrets.S3_BUCKET}}-${{ github.event.pull_request.number }}


jobs:
  move-content:
    name: "Move content to non prod"
    runs-on: ubuntu-latest
    environment:
      name: nonprod
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Check if bucket exist
        id: bucket_existed
        run: |
          if aws s3api head-bucket --bucket  ${{env.S3-BUCKET}} 2>/dev/null; then
            echo "Bucket already exists, skipping create step"
            echo "existed=true" >> $GITHUB_OUTPUT
          else
            echo "Bucket does not exist, proceeding with create step"
          fi

      - name: Create S3 bucket
        if: steps.bucket_existed.outputs.existed != 'true'
        run: |
          aws s3api create-bucket \
            --bucket ${{env.S3-BUCKET}}

      - name: Configure S3 bucket
        if: steps.bucket_existed.outputs.existed != 'true'
        run: |
          aws s3api put-public-access-block \
            --bucket ${{env.S3-BUCKET}} \
            --public-access-block-configuration "BlockPublicAcls=false,BlockPublicPolicy=false,IgnorePublicAcls=false,RestrictPublicBuckets=false"

      - name: Set public read policy
        run: |
          aws s3api put-bucket-policy \
            --bucket ${{env.S3-BUCKET}} \
            --policy '{
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Sid": "PublicReadGetObject",
                  "Effect": "Allow",
                  "Principal": "*",
                  "Action": "s3:GetObject",
                  "Resource": "arn:aws:s3:::${{env.S3-BUCKET}}/*"
                }
              ]
            }'

      - name: Sync files to S3 bucket
        run: | 
          aws s3 sync . s3://${{env.S3-BUCKET}} \
            --exclude '*.md' \
            --exclude '.github/*' \
            --exclude '.git/*'
      
      - name: Add description
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if (context.payload.pull_request && context.payload.pull_request.body === null) {
              github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                body: `Your pull request access link will be https://${{env.S3-BUCKET}}.s3.us-east-1.amazonaws.com/
                      \nFor example: https://${{env.S3-BUCKET}}.s3.us-east-1.amazonaws.com/images/logos/lastv.png`
              });
            } else {
              console.log("Pull request body is not null");
            }