name: "PULL REQUEST to S3"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  move-content:
    name: "Move content to non prod"
    runs-on: ubuntu-latest
    environment:
      name: nonprod
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create S3 bucket
        run: |
          aws s3api create-bucket \
            --bucket ${{secrets.S3_BUCKET}}-${{ github.event.pull_request.number }} \
            --create-bucket-configuration LocationConstraint=us-east-1

      - name: Sync files to S3 bucket
        run: aws s3 sync . s3://${{secrets.S3_BUCKET}}-${{ github.event.pull_request.number }} --acl public-read
